import Config

# Configure your database
config :suchteam, Suchteam.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5432,
  database: "suchteam_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :suchteam, SuchteamWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "PxAXcaaE8MZ91TWnD5X7lPnNhHyEhTqBjW5CJIhS7YQL3lfwE0BcSiMt1kM04sNX",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:suchteam, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:suchteam, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :suchteam, SuchteamWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/suchteam_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :suchteam, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :suchteam, Oban,
  repo: Suchteam.Repo,
  queues: [tasks: 10, default: 5],
  plugins: [Oban.Plugins.Pruner]

config :suchteam, :open_claw,
  gateway_url: System.get_env("OPENCLAW_GATEWAY_URL") || "ws://localhost:18789",
  http_url: System.get_env("OPENCLAW_HTTP_URL") || "http://localhost:18789",
  token: System.get_env("OPENCLAW_GATEWAY_TOKEN"),
  reconnect_interval: 5000,
  enabled: System.get_env("OPENCLAW_ENABLED") == "true"

config :suchteam, :redis, url: System.get_env("REDIS_URL") || "redis://localhost:6379"

config :swoosh, :api_client, false
